Fix nanohttp_stream build with external libxml2.
areaDetector/ADSupport pull request #41
Opened 2023-08-03 11:22 UTC by ericonr

Commit 2e167d2bd5a002b079589abb32b4e454e234355e defined IN_LIBXML unconditionally inside nanohttp_stream.c, which, when building on Linux with external libxml2, leads to multiple linking errors, since the redirections from "elfgcchack.h" are still included. The symbols will only be available when building the library inside ADSupport, so we can only define IN_LIBXML in that case. Since the added compiler flag will apply to all files, we can omit the "#define IN_LIBXML" line from them.

@MarkRivers, could you please check that this doesn't regress the build which commit 2e167d2bd5a002b079589abb32b4e454e234355e aimed to fix?

2023-08-03 16:31 UTC, MarkRivers requested changes
I don't think it is necessary to modify all of the source files to remove this line:
```
#define IN_LIBXML
```
I want to have the absolute minimum modifications to the upstream xml2 library source code to make upgrading to the next version as simple as possible.

2023-08-03 18:40 UTC, ericonr commented
I hadn't considered that! Done

2023-11-10 18:25 UTC, ericonr commented
Hi @MarkRivers !
Gentle ping :)

2023-11-10 18:55 UTC, MarkRivers requested changes
This change to the Makefile will compile all files in this directory with -DIN_LIBXML.  That is dangerous, since perhaps there are some files that should not be compiled with that flag.

EPICS supports supplying flags for just a specific file.  This is described on page 77 of this document: https://epics.anl.gov/base/R3-16/2-docs/AppDevGuide.pdf

`<name>_CFLAGS file specific C compiler flags (e.g. xxxRecord CFLAGS=-g)`

So I think you can change the Makefile line to be:
`nanohttp_stream_CFLAGS = -DIN_LIBXML`

Please test this and see if it works.  If so then update the PR.
Thanks

2023-11-10 19:00 UTC, MarkRivers requested changes
There is another problem with your change to the Makefile.  You used 
`USR_CFLAGS` = -DIN_LIBXML`

That will remove any CFLAGS that are already defined, for example on Lines 16 and 21.  You need to change that to +=, not =.

2023-11-16 16:16 UTC, merged